version: "3"
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - env
    networks:
     - djangonetwork
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    env_file:
      - env.dev
    networks:
     - djangonetwork

networks:
   djangonetwork:
     driver: bridge